kind: Pod
apiVersion: v1
metadata:
  name: aspnet-configmap
spec:
  containers:
  - image: microsoft/aspnet:4.7.1-windowsservercore-1709
    name: aspnet-configmap
    env:
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.how
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: special-config
