---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-azuredisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx
      name: deployment-azuredisk
    spec:
      containers:
      - name: deployment-azuredisk
        image: nginx
        command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/blobdisk/outdisk; sleep 1; done		
        volumeMounts:
        - name: blobdisk01
          mountPath: "/mnt/blobdisk"
      volumes:
      - name: blobdisk01
        persistentVolumeClaim:
          claimName: pvc-azuredisk
